---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: kubesphere-system
  labels:
    app: kubesphere
spec:
  selector:
    app: kubesphere
  ports:
    - name: tcp
      protocol: TCP
      port: 2379
      targetPort: 2379

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd
  namespace: kubesphere-system
  labels:
    app: kubesphere
spec:
  serviceName: "etcd"
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: etcd-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        # storageClassName: ""
        resources:
          requests:
            storage: 2Gi
  template:
    metadata:
      labels:
        app: kubesphere
    spec:
      containers:
        - name: etcd
          image: quay.azk8s.cn/coreos/etcd:v3.2.18
          imagePullPolicy: IfNotPresent
          command:
            [
              "etcd",
              "--data-dir=/data",
              "--listen-client-urls=http://0.0.0.0:2379",
              "--advertise-client-urls=http://etcd.kubesphere-system.svc:2379",
              "--max-snapshots=5",
              "--max-wals=5",
              "--auto-compaction-retention=168",
            ]
          ports:
            - containerPort: 2379
              name: etcd
          volumeMounts:
            - name: etcd-pvc
              mountPath: /data
