apiVersion: v1
appVersion: 1.4.0
description: Containerized Storage for Containers
home: http://www.openebs.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
keywords:
- cloud-native-storage
- block-storage
- iSCSI
- storage
maintainers:
- email: n.haoyuan@gmail.com
  name: hydrz
name: openebs-lite
sources:
- https://github.com/hydrz/helm-charts/openebs-lite
version: 1.4.0
