{{- if .Values.serviceAccount.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "openebs.storageClassName" . }}
  annotations:
    storageclass.kubesphere.io/supported_access_modes: '["ReadWriteOnce"]'
    storageclass.beta.kubernetes.io/is-default-class: {{ ternary "true" "false" .Values.storageClass.isDefaultClass | quote }}
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: {{ .Values.storageClass.basePath }}
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- end }}

