apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - hydrz"
  labels:
    app: spring-cloud-data-flow
    chart: spring-cloud-data-flow-2.2.2.RELEASE
    fullname: spring-cloud-data-flow
    heritage: Tiller
    release: spring-cloud-data-flow
  name: spring-cloud-data-flow
  namespace: spring
spec:
  rules:
    - host: dataflow.hydrz.cn
      http:
        paths:
          - backend:
              serviceName: dataflow-data-flow-server
              servicePort: 80
  tls:
    - hosts:
        - dataflow.hydrz.cn
      secretName: dataflow-tls
